name: Build wheels with cibuildwheel

on:
  workflow_dispatch:
    inputs:
      cuda-version:
        description: "CUDA toolkit version"
        required: true
        default: "13.0.0"
      torch-version:
        description: "PyTorch version"
        required: true
        default: "2.9.0"
jobs:
  build_wheels:
    name: Build wheels
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-22.04-arm, windows-2025]
    env:
      CIBW_ARCHS: auto64
      CIBW_ARCHS_WINDOWS: AMD64
      CUDA_VERSION: ${{ github.event.inputs.cuda-version || '13.0.0' }}
      TORCH_VERSION: ${{ github.event.inputs.torch-version || '2.4.0' }}
      CIBW_BUILD_FRONTEND: "build; args: --no-isolation"
      CIBW_ENVIRONMENT: |
        NVCC_THREADS=2
        MAX_JOBS=1
        FLASH_ATTENTION_SKIP_CUDA_BUILD=FALSE
        FLASH_ATTENTION_FORCE_BUILD=TRUE
      CIBW_ENVIRONMENT_PASS_LINUX: "CUDA_VERSION TORCH_VERSION"
      CIBW_ENVIRONMENT_PASS_WINDOWS: "CUDA_VERSION TORCH_VERSION"
      CIBW_ENVIRONMENT_WINDOWS: |
       CUDA_HOME=%CUDA_PATH%
       PATH=%CUDA_HOME%\bin;%PATH%
      CIBW_BUILD: cp310-* cp311-* cp312-* cp313-*
      CIBW_BEFORE_ALL_LINUX: .github/workflows/scripts/prepare_build_environment_linux.sh
      CIBW_BEFORE_ALL_WINDOWS: bash .github/workflows/scripts/prepare_build_environment_windows.sh
      CIBW_BEFORE_BUILD: bash .github/workflows/scripts/install_torch.sh
      CIBW_MANYLINUX_X86_64_IMAGE: manylinux_2_28
      CIBW_MANYLINUX_AARCH64_IMAGE: manylinux_2_28
      CIBW_SKIP: "pp* *musllinux* *-win32"
    steps:
      - name: Enable long paths (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          git config --system core.longpaths true || echo "no system scope"
          git config --global core.longpaths true
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 1
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Build wheels
        uses: pypa/cibuildwheel@v3.1.4
      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: wheelhouse/*.whl

  publish_pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: build_wheels
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download wheels artifact
        uses: actions/download-artifact@v4
        with:
          path: wheelhouse
          pattern: wheels-*
          merge-multiple: true

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.12.4
        with:
          packages: wheelhouse/*.whl
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
